config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :search, only: %i[new index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    if params[:query].present?
      @tracks = RSpotify::Track.search(params[:query])
    else
      redirect_to new_search_path, alert: 'Please enter a search query.'
    end
  end
  def new
    # 検索フォームの表示
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspotifySample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>
<!-- app/views/search/index.html.erb -->
<% if @tracks %>
  <ul>
    <% @tracks.each do |track| %>
      <li>
        <%= track.name %> - <%= track.artists.first.name %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/search/new.html.erb
<h1>Search#new</h1>
<p>Find me in app/views/search/new.html.erb</p>
<%= form_tag search_index_path, method: :get do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search" %>
<% end %>